######################################################################
# Automatically generated by qmake (3.0) niedz. lip 19 17:50:42 2015
######################################################################

TEMPLATE = app
TARGET = bixi-unit-tests
INCLUDEPATH += . ../PhysicalObjects ../Utilities ../UnitTests ../Universe
LIBS += -lCppUTest
CONFIG -= qt
CONFIG += c++11

# Input
HEADERS += ../PhysicalObjects/PhysicalObject.h \
           ../PhysicalObjects/PhysicalObjectType.h \
           ../PhysicalObjects/Spacecraft.h \
           ../PhysicalObjects/SphericalObject.h \
           ../UnitTests/unit_tests_tools.h \
           ../Universe/PhysicalObjectsContainer.h \
           ../Universe/Tracker.h \
           ../Utilities/Assert.h \
           ../Utilities/BasicDefinitions.h \
           ../Utilities/PhysicalDefinitions.h \
           ../Utilities/Vector.h \
           ../Utilities/CyclicBuffer.h 
SOURCES += ../PhysicalObjects/PhysicalObject.cpp \
           ../PhysicalObjects/Spacecraft.cpp \
           ../PhysicalObjects/SphericalObject.cpp \
           ../UnitTests/main_ut.cpp \
           ../UnitTests/test_PhysicalObject.cpp \
           ../UnitTests/test_PhysicalObjectsContainer.cpp \
           ../UnitTests/test_SphericalObject.cpp \
           ../UnitTests/test_Vector.cpp \
           ../UnitTests/test_Tracker.cpp \
           ../UnitTests/test_CyclicBuffer.cpp \
           ../UnitTests/unit_tests_tools.cpp \
           ../Universe/PhysicalObjectsContainer.cpp \
           ../Universe/Tracker.cpp \
           ../Utilities/PhysicalDefinitions.cpp \
           ../Utilities/Vector.cpp
