######################################################################
# Automatically generated by qmake (3.0) pt. wrz 4 16:52:54 2015
######################################################################

TEMPLATE = app
TARGET = bixi-unit-tests
INCLUDEPATH += ../PhysicalObjects ../Utilities ../UnitTests ../Universe
LIBS += -lCppUTest
CONFIG -= qt
CONFIG += c++11

# Input
HEADERS += ../PhysicalObjects/PhysicalObject.h \
           ../PhysicalObjects/PhysicalObjectType.h \
           ../PhysicalObjects/Spacecraft.h \
           ../PhysicalObjects/SphericalObject.h \
           ../UnitTests/unit_tests_tools.h \
           ../Universe/CollisionComparator.h \
           #../Universe/DataLoader.h \
           ../Universe/PhysicalObjectProperties.h \
           ../Universe/PhysicalObjectsContainer.h \
           ../Universe/PrecisionTester.h \
           ../Universe/Tracker.h \
           #../Universe/Universe.h \
           ../Utilities/Assert.h \
           ../Utilities/BasicDefinitions.h \
           ../Utilities/Color.h \
           ../Utilities/CyclicBuffer.h \
           ../Utilities/Math.h \
           ../Utilities/PhysicalDefinitions.h \
           ../Utilities/Vector.h
SOURCES += ../PhysicalObjects/PhysicalObject.cpp \
           ../PhysicalObjects/Spacecraft.cpp \
           ../PhysicalObjects/SphericalObject.cpp \
           ../UnitTests/main_ut.cpp \
           ../UnitTests/test_CyclicBuffer.cpp \
           ../UnitTests/test_Math.cpp \
           ../UnitTests/test_PhysicalObject.cpp \
           ../UnitTests/test_PhysicalObjectsContainer.cpp \
           ../UnitTests/test_SphericalObject.cpp \
           ../UnitTests/test_Tracker.cpp \
           ../UnitTests/test_Vector.cpp \
           ../UnitTests/unit_tests_tools.cpp \
           #../Universe/DataLoader.cpp \
           ../Universe/PhysicalObjectProperties.cpp \
           ../Universe/PhysicalObjectsContainer.cpp \
           ../Universe/PrecisionTester.cpp \
           ../Universe/Tracker.cpp \
           #../Universe/Universe.cpp \
           ../Utilities/Math.cpp \
           ../Utilities/PhysicalDefinitions.cpp \
           ../Utilities/Vector.cpp
